#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export WEKNORA_DEV_DATA_MODE=named-volume
unset WEKNORA_DEV_DATA_ROOT
unset WEKNORA_DEV_POSTGRES_DATA_MOUNT
unset WEKNORA_DEV_REDIS_DATA_MOUNT
unset WEKNORA_DEV_MINIO_DATA_MOUNT
unset WEKNORA_DEV_QDRANT_DATA_MOUNT
unset WEKNORA_DEV_OPENSEARCH_DATA_MOUNT
unset WEKNORA_DEV_MILVUS_DATA_MOUNT
unset WEKNORA_DEV_NEO4J_DATA_MOUNT
unset WEKNORA_DEV_DOCREADER_TMP_MOUNT
unset WEKNORA_DEV_SEARXNG_CONFIG_MOUNT
unset WEKNORA_APP_DATA_MOUNT
unset WEKNORA_POSTGRES_DATA_MOUNT
unset WEKNORA_DOCREADER_TMP_MOUNT
unset WEKNORA_MINIO_DATA_MOUNT
unset WEKNORA_QDRANT_DATA_MOUNT
unset WEKNORA_NEO4J_DATA_MOUNT
unset WEKNORA_MILVUS_DATA_MOUNT
unset WEKNORA_WEAVIATE_DATA_MOUNT

exec "$SCRIPT_DIR/dev.sh" "$@"
