#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

export WEKNORA_DEV_DATA_MODE=host-data
export WEKNORA_DEV_DATA_ROOT="${WEKNORA_DEV_DATA_ROOT:-$PROJECT_ROOT/.local-data/dev-compose}"

mkdir -p \
  "$WEKNORA_DEV_DATA_ROOT/postgres" \
  "$WEKNORA_DEV_DATA_ROOT/redis" \
  "$WEKNORA_DEV_DATA_ROOT/minio" \
  "$WEKNORA_DEV_DATA_ROOT/qdrant" \
  "$WEKNORA_DEV_DATA_ROOT/opensearch" \
  "$WEKNORA_DEV_DATA_ROOT/milvus" \
  "$WEKNORA_DEV_DATA_ROOT/neo4j" \
  "$WEKNORA_DEV_DATA_ROOT/docreader-tmp" \
  "$WEKNORA_DEV_DATA_ROOT/searxng-config" \
  "$WEKNORA_DEV_DATA_ROOT/app-files" \
  "$WEKNORA_DEV_DATA_ROOT/weaviate"

export WEKNORA_DEV_POSTGRES_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/postgres"
export WEKNORA_DEV_REDIS_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/redis"
export WEKNORA_DEV_MINIO_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/minio"
export WEKNORA_DEV_QDRANT_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/qdrant"
export WEKNORA_DEV_OPENSEARCH_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/opensearch"
export WEKNORA_DEV_MILVUS_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/milvus"
export WEKNORA_DEV_NEO4J_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/neo4j"
export WEKNORA_DEV_DOCREADER_TMP_MOUNT="$WEKNORA_DEV_DATA_ROOT/docreader-tmp"
export WEKNORA_DEV_SEARXNG_CONFIG_MOUNT="$WEKNORA_DEV_DATA_ROOT/searxng-config"

export WEKNORA_APP_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/app-files"
export WEKNORA_POSTGRES_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/postgres"
export WEKNORA_DOCREADER_TMP_MOUNT="$WEKNORA_DEV_DATA_ROOT/docreader-tmp"
export WEKNORA_MINIO_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/minio"
export WEKNORA_QDRANT_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/qdrant"
export WEKNORA_NEO4J_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/neo4j"
export WEKNORA_MILVUS_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/milvus"
export WEKNORA_WEAVIATE_DATA_MOUNT="$WEKNORA_DEV_DATA_ROOT/weaviate"

exec "$SCRIPT_DIR/dev.sh" "$@"
